# Generated by Django 3.2.8 on 2021-10-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0002_auto_20211011_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateField(verbose_name='Date_joined'),
        ),
    ]
