# Generated by Django 3.2.8 on 2021-10-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0003_alter_enrollment_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
