# Generated by Django 3.2.8 on 2021-10-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApp', '0004_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
